RMI-PACTA/app

pacta/BUILD.bazel, pacta/clone_test.go, pacta/enum_test.go, pacta/pacta.go
Includes basic testing for clone + parse
=> Initial golang Domain Types

frontend/app.vue, frontend/components/modal/Error.vue, frontend/components/standard/Debug.vue, frontend/composables/newModal.ts, frontend/composables/useAPI.ts, frontend/error.vue, frontend/globalimports/present.ts, frontend/layouts/default.vue, frontend/lib/error/index.ts, frontend/pages/admin/index.vue, frontend/pages/admin/pacta-version/[id].vue, frontend/pages/admin/pacta-version/index.vue, frontend/pages/admin/pacta-version/new.vue
This PR gets the SSR ball rolling, such that API requests can now be served via SSR. This is basically just sprinkling `useAsyncData` around and forwarding client cookies during SSR in `useAPI`.
This PR also has a kinda related refactoring of error handling stuff.
Now, all error management is done by just `throw`-ing things.
* API returns a non-2xx code? **Throw it** (Axios/the codegen does this for us)
* API response contains an error? **Throw it** (currently in `handleOAPIError`, will go away with #10)
* Error from your `useAsyncData`? **Throw it**
* Data you require is unexpectedly null? **Throw it**
We use [`createError`](https://nuxt.com/docs/getting-started/error-handling#createerror) for everything now, as it gives us a standardized interface to put metadata in, which we can then …
=> Add support for SSR, revamp error handling

openapi/pacta.yaml
Fixes #25 + adds an example for `error_id`
=> Assorted OpenAPI spec clean ups

cmd/server/pactasrv/initiative.go, cmd/server/pactasrv/pacta_version.go, frontend/openapi/generated/pacta/services/DefaultService.ts, frontend/pages/admin/pacta-version/index.vue, openapi/pacta.yaml
This is more semantically accurate and generates the expected `void` response in the frontend client code, see https://github.com/ferdikoomen/openapi-typescript-codegen/issues/607
=> Use HTTP 204 No Content for endpoints without response bodies

.github/workflows/ci.yml, .github/workflows/deploy.yml
This PR adds a GitHub Actions workflow that builds, tests, and then deploys both the PACTA frontend and backend.
It also cleans up some naming + stuff on the CI action.
Signed-off-by: Brandon Sprague <brandon@sprague.mx>
=> Add PACTA deployment workflow for GitHub Actions

.github/workflows/deploy.yml
You can see a succeeding run in [1], though it also required a few changes to the Terraform config, which have gone out in https://github.com/Silicon-Ally/rmi-terraform/pull/4
[1] https://github.com/RMI-PACTA/app/actions/runs/6399561267/job/17372351732
Signed-off-by: Brandon Sprague <brandon@sprague.mx>
=> Fix typo in deploy workflow

frontend/.eslintrc.json, frontend/composables/useAPI.ts, frontend/composables/useMSAL.ts, frontend/composables/usePACTA.ts, frontend/envs/env.dev, frontend/envs/env.local, frontend/middleware/admin.ts, frontend/nuxt.config.ts, frontend/package-lock.json, frontend/package.json, frontend/pages/admin/pacta-version/[id].vue, frontend/pages/admin/pacta-version/index.vue, frontend/pages/admin/pacta-version/new.vue, frontend/plugins/msal.client.ts
Update MSAL integration, mirrors changes we did to OPGEE with some PACTA-specific differences. More specifically:
- **Stay logged in between requests** - Before, if you refreshed the page, you were logged out. Very annoying. This is no longer the case.
- **Cache Azure credentials** - Since the credsrv token + and the Azure ID token expire at the same time, we can use the 'cached' status of the Azure token to decide if we need to refresh our own auth
- **Update MSAL to the latest version**
=> Overhaul auth management

azure/azevents/azevents.go, cmd/server/configs/dev.conf, cmd/server/configs/local.conf, cmd/server/main.go, scripts/run_server.sh, secrets/local.enc.json
This PR finishes up the work of validating requests from Event Grid, and adds support for running the server with a public-facing endpoint via the `--with_public_endpoint=<subdomain>` flag, which is proxied via [frp](https://github.com/fatedier/frp).
I didn't use our [frpembed](https://github.com/Silicon-Ally/frpembed) library because there's an issue with `quic-go` not supporting Go 1.20 (may be fixed, didn't want to go down the rabbithole)
=> Finish adding Event Grid validation, and add local testing tools

azure/azevents/azevents.go, cmd/server/main.go, scripts/run_server.sh, secrets/local.enc.json
This PR adds support for a shared secret that gets sent with webhook HTTP requests, so that we can validate they came from Azure.
It also adds local support for testing webhooks, which works something like:
1. Developer starts a local server with `--with_public_endpoint=XYZ`
2. Script checks if `local-webhook-XYZ` already exists
3. If not, asks user if they want to create one
4. If yes, waits for server to start (needed for verification to succeed), then creates the webhook
=> Add webhook auth for Event Grid  webhooks, and local infra

cmd/runner/main.go
Specifically, add the `task_id` to log lines in the runner so we can figure out how long tasks are taking from the log output.
=> Address some feedback from #45

.github/workflows/deploy.yml, cmd/runner/BUILD.bazel, cmd/runner/main.go, cmd/server/BUILD.bazel, cmd/server/configs/local.conf, cmd/server/main.go, task/task.go
A simple cost saving measure, since each of our (currently) four RMI registries costs like $1/day. I noticed it when checking our Azure credit burn rate.
=> Merge various RMI container registries

openapi/pacta.yaml, openapi/user.yaml
Runs [google/yamlfmt](https://github.com/google/yamlfmt) over our openapi definitions.
=> Standardizes YAML Formatting

azure/azevents/azevents.go, cmd/runner/configs/dev.conf, cmd/runner/configs/local.conf, cmd/runner/main.go, cmd/runner/taskrunner/taskrunner.go, cmd/server/configs/dev.conf, cmd/server/configs/local.conf, cmd/server/main.go, cmd/server/pactasrv/pactasrv.go, cmd/server/pactasrv/portfolio.go, frontend/openapi/generated/pacta/index.ts, frontend/openapi/generated/pacta/models/Error.ts, frontend/openapi/generated/pacta/models/ParsePortfolioReq.ts, frontend/openapi/generated/pacta/models/ParsePortfolioResp.ts, frontend/openapi/generated/pacta/services/DefaultService.ts, frontend/pages/admin/portfolio_test.vue, openapi/pacta.yaml, scripts/run_server.sh, task/task.go
I'll wait to confirm https://github.com/RMI/terraform/pull/18 is complete before submitting.
=> Renames "process" step to "parse"

cmd/server/pactasrv/BUILD.bazel, cmd/server/pactasrv/pactasrv.go, cmd/server/pactasrv/upload.go, openapi/pacta.yaml
The request is two step: (a) create the upload URLs and blobs, then after the assets are uploaded (b) kick off a process for parsing explicitly.
Sending the PR for the interface first - trying to get smaller ones going.
=> Creates Structure for Upload Requests

cmd/runner/configs/dev.conf, cmd/runner/configs/local.conf
Causes portfolio parsing test to fail with:
```
failed to parse flags: configuration variable provided but not defined: azure_event_parsed_portfolio_topic
```
=> Fix typo in runner config

frontend/plugins/msal.ts
EDIT: found the error locally, it was `userClientWithAuth` that was out of order, fixed in this PR as well
I saw an error in dev (which I haven't been able to replicate) about some minified function/variable begin referenced before its definition, and I think it might be this, which can now be eagerly invoked in `handleResponse` as we do initialization synchronously
In any case, it probably doesn't hurt
=> Reorder MSAL plugin functions

frontend/app.vue, frontend/components/modal/Error.vue, frontend/composables/useModal.ts, frontend/package-lock.json, frontend/package.json
This PR makes it so that we serialize errors if we're going to send them across the SSR boundary. The problem this fixes is that some errors (like Nuxt reporting composable usage outside a `setup` function) have functions and other non-POJO/non-serializable info with them, which makes our `useState<Error>` implode, ironically hiding the original error.
This introduces a new non-dev dependency (which I don't do lightly) on `serialize-error`, a small (<1kB min + gzip'd) and popular dependency for doing the surprisingly nontrivial task of serializing different types of errors and preserving type information.
=> Serialize errors we encounter

cmd/server/pactasrv/BUILD.bazel, cmd/server/pactasrv/conv/helpers.go, cmd/server/pactasrv/conv/pacta_to_oapi.go, cmd/server/pactasrv/initiative.go, cmd/server/pactasrv/initiative_portfolio_relationship.go, cmd/server/pactasrv/populate.go, cmd/server/pactasrv/portfolio.go, db/sqldb/portfolio.go, db/sqldb/portfolio_group.go, db/sqldb/portfolio_group_test.go, db/sqldb/snapshot.go, db/sqldb/sqldb.go, openapi/pacta.yaml, pacta/pacta.go
Also: refactors some naming conventions to make memberships more consistently named.
NOTE - this PR demonstrates the two strategies we'll use for relational object population. On high-cardinality relationships (i.e. Portfolios that are members of an Initiative) we'll populate them only on single-object retrievals, using the `get relationships` type DB methods. On low cardinality relationships (i.e. Initiatives that are attached to a portfolio), we'll populate the membership as an empty shell object on the entity, and use the `populateX` resolver helpers to populate the full thing. See that in this PR, despite the relationship being the same one, we use one strategy when looking up an initiative (which may have tens of thousands of portfolios) vs looking up a portfolio (which may have 1-2 …
=> Portfolio:Initiative Membership Backend

cmd/server/pactasrv/BUILD.bazel, cmd/server/pactasrv/audit_logs.go, cmd/server/pactasrv/conv/BUILD.bazel, cmd/server/pactasrv/conv/helpers.go, cmd/server/pactasrv/conv/oapi_to_pacta.go, cmd/server/pactasrv/conv/pacta_to_oapi.go, cmd/server/pactasrv/pactasrv.go, db/queries.go, db/sqldb/audit_log.go, db/sqldb/audit_log_test.go, db/sqldb/golden/human_readable_schema.sql, db/sqldb/golden/schema_dump.sql, db/sqldb/migrations/0007_audit_log_actor_type.down.sql, db/sqldb/migrations/0007_audit_log_actor_type.up.sql, db/sqldb/sqldb_test.go, openapi/pacta.yaml, pacta/pacta.go
- Creates API layer for Audit Log Queries (largely mirroring the database layer - I'm thinking of how lovely and useful that approach was for ABOUND, and seeking to replicate it here, albeit for likely a less user-visible use case).
- Tweaks a few things I got wrong in the initial audit log design:
- we want the `ActorType` to refer to the **pathway through which the user is accessing**, rather than **the property of the user**. This unfortunately required a DB migration to add the new enum values.
- Adds a `ParseSortBy` method to the DB Layer.
- Tweaks naming to be more consistent with the core types.
=> Audit Log API Layer

cmd/server/pactasrv/conv/BUILD.bazel, cmd/server/pactasrv/conv/conv_test.go, cmd/server/pactasrv/conv/oapi_to_pacta.go, cmd/server/pactasrv/conv/pacta_to_oapi.go, cmd/server/pactasrv/initiative.go, cmd/server/pactasrv/user.go, openapi/pacta.yaml
- Adds an enum prefix for every OpenAPI enum type, to avoid collisions + clean up the namespace (otherwise constants like `api.En` are generated).
- Removes use of YAML feature I hadn't understood prior (anchors + links), putting everything into the `schemas`, since `definitions` look like they're a Swagger (OAPI2.0) construct.
- Adds some basic Enum Round-Trip unit tests to pactasrv/conv
- removes usage of `pacta.ParseX` functions within the conv package, since these are less reliable than using the one for one, switch driven converters.
=> Various Enum Fixes + Tweaks

cmd/server/pactasrv/BUILD.bazel, cmd/server/pactasrv/admin.go, cmd/server/pactasrv/blobs.go, cmd/server/pactasrv/conv/oapi_to_pacta.go, cmd/server/pactasrv/conv/pacta_to_oapi.go, cmd/server/pactasrv/pactasrv.go, cmd/server/pactasrv/user.go, db/sqldb/BUILD.bazel, db/sqldb/audit_log.go, db/sqldb/audit_log_test.go, db/sqldb/golden/human_readable_schema.sql, db/sqldb/golden/schema_dump.sql, db/sqldb/merge.go, db/sqldb/merge_test.go, db/sqldb/migrations/0009_add_transfer_audit_log_action.down.sql, db/sqldb/migrations/0009_add_transfer_audit_log_action.up.sql, db/sqldb/migrations/0009_support_user_merge.down.sql, db/sqldb/migrations/0009_support_user_merge.up.sql, db/sqldb/owner.go, db/sqldb/sqldb.go, db/sqldb/sqldb_test.go, db/sqldb/user.go, db/sqldb/user_test.go, openapi/pacta.yaml, pacta/pacta.go
User Merge is apparently a frequent support flow, and required some delicate thinking around audit logs. This PR implements the backend for it.
Additional changes:
- Adds a new audit log type for `TRANSFER_OWNERSHIP`
- Creates a `DeleteOwner` DB method
- Updates `DeleteUser` to do the recursive deletion of their owned assets + return blobURIs
- Updates `/delete-user` to delete the downstream blobs.
=> Creates Backend for Merging User Accounts

azure/azevents/azevents.go, cmd/runner/configs/dev.conf, cmd/runner/configs/local.conf, cmd/runner/main.go, cmd/server/configs/dev.conf, cmd/server/configs/local.conf, cmd/server/main.go, scripts/run_server.sh, secrets/local.enc.json
Managing the machinery for three topics is too annoying, and it's easier and quicker and generally better to do this than set up all the local + deployed resources to make N topics work.
Instead, we use the `EventType` of a notification to indicate, well, the type of the event (e.g. `parsed-portfolio`, `created-report`, etc)
I'll send out the associated Terraform changes momentarily
=> Use a single Azure topic for all our async notifications

azure/aztask/aztask.go, cmd/server/BUILD.bazel, cmd/server/configs/local.conf, cmd/server/main.go, secrets/secrets.go
It turns out that the way Azure intends you to use Container Apps Jobs is to create a single 'job' and then invoke it (optionally changing the command/image/etc).
'Jobs' are more like 'templates', and are fairly heavy to create. This PR changes our config to just run things against and existing ACAJ, which makes everything much faster.
=> Don't create a new Azure Container Apps Job (ACAJ) every time

frontend/composables/useURLParams.ts
Discussed offline the need for something like this, @bcspragu  had the bright idea to use `watch` on the current route, which ended up being the thing that clinched this working.
We'll be able to back-export this to a bunch of other projects once agreed upon!
=> Allows Computed URL Parameters to not overwrite one another

cmd/server/pactasrv/analysis.go, cmd/server/pactasrv/conv/conv_test.go, cmd/server/pactasrv/conv/oapi_to_pacta.go, frontend/components/portfolio/ListView.vue, frontend/openapi/generated/pacta/index.ts, frontend/openapi/generated/pacta/models/AuditLogAction.ts, frontend/openapi/generated/pacta/models/MergeUsersReq.ts, frontend/openapi/generated/pacta/models/MergeUsersResp.ts, frontend/openapi/generated/pacta/services/DefaultService.ts
Fix a few unrelated issues that came up while testing non-parse-portfolio async tasks
Also adds a basic `Test Run Analysis` button to the `PortfolioListView` to help test stuff
=> Update generated OAPI bindings, fix enum conv, other small bugs

cmd/runner/README.md, cmd/runner/main.go, cmd/server/pactasrv/analysis.go, db/sqldb/blob.go, db/sqldb/golden/human_readable_schema.sql, db/sqldb/golden/schema_dump.sql, db/sqldb/migrations/0011_add_report_file_types.down.sql, db/sqldb/migrations/0011_add_report_file_types.up.sql, db/sqldb/sqldb_test.go, frontend/i18n.config.ts, frontend/plugins/handle-missing-translation.ts, pacta/pacta.go, scripts/BUILD.bazel, scripts/build_and_load_runner.sh
This PR makes assorted tweaks to the runner's `create-report` task, like:
- Adding new `pacta.FileType`s for assorted HTML-adjacent types present in the report (see below)
- Includes an `UNKNOWN` type in case I miss anything, we can always go back and re-label them based on file extension
- Fix some issues with paths, use the portfolio UUID as the directory prefix (to avoid collisions)
- Publish the event when we're done so the main app can record the info
Mostly unrelated changes:
- Fixes #135 by pulling `handleMissingTranslation` from the `$nuxt` object instead of `inject`
- Add a helper script for iterating quickly on the runner, `build_and_load_runner.sh`
Some resources that get created from this:
```
select * from blob WHERE blob_uri LIKE 'az://reports/%';
id             | …
```
=> Get the `create-report` async task in shape

cmd/server/BUILD.bazel, cmd/server/main.go, reportsrv/BUILD.bazel, reportsrv/reportsrv.go, reportsrv/reportsrv_test.go
This PR adds a new `/report/<analysis ID>` endpoint that serves a report. Importantly, this is a _server_ endpoint, our Nuxt client knows nothing about it.
That means to test it locally, you go to `localhost:8081/report/<analysis ID>`, and when deployed, it'll be `https://pacta-api.dev.rmi.siliconally.dev/report/<analysis ID>` IIRC. Since we share cookies between `*.dev.rmi.siliconally.dev`, this works fine.
The main thing missing from this PR is authz, which will be the next thing I do.
=> Add support for serving the static assets in a report

WORKSPACE, cmd/tools/migratesqldb/cmd/BUILD.bazel, cmd/tools/migratesqldb/cmd/cmd.go, deps.bzl, go.mod, go.sum, scripts/run_db.sh, scripts/shared/migrate.sh
We had the `rollback_db` script, but had lost `migratesqldb rollback` at some point down the line, this adds that back.
I also ended up updating some of our deps because:
1. I noticed that `bazel.Runfiles` was deprecated
2. ...so I installed the suggested replacement of `github.com/bazelbuild/rules_go/go/runfiles`
3. ...and that caused `golang.org/x/tools` to update
4. ...and that caused `//:nogo` to stop compiling
5. ...which broke all of our builds
And updating to the latest `rules_go` and `gazelle` fixed that, and I updated us to Go 1.21 for good measure as well.
=> Add rollback support to `migratedb` and update deps

scripts/run_db.sh
This makes the setup work for podman and un-breaks normal Docker setups, see comments in `run_db.sh` for details
=> Fix flags in local DB running script

cmd/server/pactasrv/user.go, frontend/assets/css/overrides.css, frontend/components/form/FieldHeader.vue, frontend/components/inputs/EngagementStrategy.vue, frontend/components/inputs/Esg.vue, frontend/components/inputs/External.vue, frontend/components/language/Selector.vue, frontend/components/portfolio/ListView.vue, frontend/components/portfolio/group/ListView.vue, frontend/components/portfolio/group/NewModal.vue, frontend/composables/useLocalStorage.ts, frontend/lang/en.json, frontend/lib/editor/common.ts, frontend/lib/editor/incomplete_upload.ts, frontend/lib/editor/portfolio.ts, frontend/lib/editor/utils.ts, frontend/pages/upload.vue
=> Bug Bash #2

cmd/tools/migratesqldb/cmd/cmd.go
`testpgx` handled this for us before, but I forgot that `migrate.Up()` returns an `ErrNoChange` error when there's no migrations to apply, which is annoying and causes `:run_db` to fail
=> Fix DB migration

cmd/server/pactasrv/analysis.go, cmd/server/pactasrv/conv/pacta_to_oapi.go, db/sqldb/blob.go, frontend/components/analysis/Editor.vue, frontend/components/analysis/ListView.vue, frontend/components/portfolio/ListView.vue, frontend/lang/en.json, frontend/lib/editor/analysis.ts, frontend/lib/editor/index.ts, frontend/pages/my-data.vue, openapi/pacta.yaml, reportsrv/BUILD.bazel, reportsrv/reportsrv.go, reportsrv/reportsrv_test.go
- Adds a simple FE for report display to the `my-data` page.
- Adds a `view` button which allows a user to see the report, with a few failures.
- Fixes an issue that wouldn't allow analyses to be listed appropriately (missing their artifact + blob population)
- Fixes missing `api` FileType enums
- Adds Audit Logging + Authorization Checking to the Streaming endpoint
=> Barebones Analysis Display + Audit Logs

frontend/components/analysis/ListView.vue, frontend/components/incompleteupload/ListView.vue, frontend/components/portfolio/ListView.vue, frontend/components/portfolio/group/ListView.vue, frontend/pages/incomplete-uploads.vue
This PR was done through a Find + Replace.
Searched for:
`editorValues.value.([^.]*).originalValue`
Replaced With:
`currentValue.value.$1`
=> Simplifies Accessing Current Properties on Editor Objects

cmd/server/pactasrv/initiative.go, cmd/server/pactasrv/pactasrv.go, cmd/server/pactasrv/portfolio_group.go, db/sqldb/initiative.go, db/sqldb/initiative_test.go, db/sqldb/owner.go, db/sqldb/portfolio.go, db/sqldb/portfolio_group.go, db/sqldb/portfolio_group_test.go, db/sqldb/snapshot.go
- Deletes analysis based on a Portfolio if the portfolio gets deleted (satisfying the constraint we've implicitly encoded through the FKC's on the `portfolio_snapshot`'s fields).
- Does the same for `portfolio_group` and `initiative` (though we can't yet run analyses based on these)
- Because this changes the signatures to return `[]pacta.BlobURI` on deletes, adds blob deletion code to the API.
NOTE: I haven't been able to validate through running locally that the deletes for PGs or Initaitives work when this is run because we don't have the ability to run portfolio group or initaitive based analyeses yet.
=> Recursive Deletes

cmd/server/pactasrv/conv/pacta_to_oapi.go, frontend/components/SharedToPublicToggleButton.vue, frontend/components/analysis/ListView.vue, frontend/components/standard/Nav.vue, frontend/lang/en.json, frontend/lib/auditlogquery/index.ts, frontend/pages/index.vue
Creates a section in the Analysis display that:
- has a toggle allowing users to bulk change ADE + STP status for all artifacts (note that individually addressable artifact sharing statuses was a SOW requirement, and that though this will definitely lead to duplicative traffic, until we have evidence it's prohibitive, we're probably OK to keep it this way
- Links to the Audit Logs for the Analysis.
Other fixes:
- Fixes a PVImage bug on the front page, the `:pt` definition had changed in the PV upgrade.
- Changes the nav to highlight as current a page if it shares the same path, even if the full-paths differ.
- Fixes an STP conversion issue.
- Fixes an Encoding issue for the audit log url.
=> Creates Access Control Section for Analyses

cmd/server/pactasrv/pactasrv.go, db/sqldb/initiative.go, db/sqldb/owner.go, db/sqldb/owner_test.go
This mirrors the behavior on `User` creates, simplifying ownership structure.
Great suggestion Brandon!
=> Creates Initiative Owner when creating an Initiative

cmd/server/pactasrv/conv/oapi_to_pacta.go, cmd/server/pactasrv/conv/pacta_to_oapi.go, cmd/server/pactasrv/portfolio.go, cmd/server/pactasrv/upload.go, frontend/components/analysis/ContextualListView.vue, frontend/components/analysis/RunButton.vue, frontend/components/inputs/HoldingsDate.vue, frontend/components/modal/Group.vue, frontend/lang/en.json, frontend/openapi/generated/pacta/models/HoldingsDate.ts, frontend/openapi/generated/pacta/models/IncompleteUpload.ts, frontend/openapi/generated/pacta/models/Portfolio.ts, frontend/openapi/generated/pacta/models/StartPortfolioUploadReq.ts, frontend/pages/upload.vue, frontend/plugins/primevue.ts, openapi/pacta.yaml
- Adds a warning when a user tries to run an analysis that is duplicative, a "nice to have" from the SOW.
- While working on this I realized there was an error in how HoldingsDate was populated + thus whether or not it could be cleared. I've fixed that bug (which required many code changes) alongside this small feature.
=> Warn about Duplicate Analyses, Allow Holdings Date to be Cleared

frontend/pages/admin/index.vue, frontend/pages/admin/merge.vue
Wildly, it seems that User Merge works out of the box - validated that groups, portfolios and other owned assets transfer over seamlessly!
:)
=> FE for User Merge, Validated

cmd/server/main.go, reportsrv/reportsrv.go
=> Allows Anonymous Downloads of Shared Assets

cmd/server/main.go
This PR disables some of our noiser logs, in particular CORS + request/response logging. As noted in the code, most of this info is provided by our cloud environment when deployed, and when local, these things are generally just noisy. They can be selectively turned on as debugging requires.
Fixes #67
=> Disable CORS + request/response logs

frontend/package.json
In shell, `;` means "run the next thing regardless", so when `eslint` failed, we just ran stylelint regardless, and that was the exit code that GH Actions saw
Using `&&` short-circuits when something fails, so if eslint fails now, GH Actions will also fail
=> Fail CI runs on lint

frontend/composables/useModal.ts, frontend/composables/usePACTA.ts, frontend/lib/error/index.ts, frontend/pages/admin/merge.vue
As discussed, this is an alternate approach to #174 for fixing #168. It handles errors directly in `withLoading` and `pactaClient`. The problem then is that both these functions return _something_, so you still have to throw and interrupt the flow of code (I originally tried just leaving hanging promises, but our linter informed me that's a really bad idea)
Since we have to throw, we throw a sentinel so that anything further up the chain knows not to render another dialog.
I tested it in a few different cases and confirmed it does what we expect.
=> Fix error modal handling

WORKSPACE, async/BUILD.bazel, async/async.go, async/req.go, azure/azcreds/BUILD.bazel, azure/azcreds/azcreds.go, cmd/parser/BUILD.bazel, cmd/parser/README.md, cmd/parser/configs/dev.conf, cmd/parser/configs/local.conf, cmd/parser/main.go, cmd/parser/taskrunner/BUILD.bazel, cmd/parser/taskrunner/taskrunner.go, cmd/runner/BUILD.bazel, cmd/runner/README.md, cmd/runner/main.go, cmd/server/main.go, deps.bzl, go.mod, go.sum, reportsrv/BUILD.bazel, scripts/BUILD.bazel, scripts/build_and_load_parser.sh
Technically, we could have used a single `runner` binary with two different base images, but that's liable to get confusing quickly, so this PR creates a new `parser` binary that is mostly just split out from the `runner`.
It also refactors a few pieces of code we've been copying around:
- `azcreds` - Logic for how to authenticate with Azure based on where we're running
- `async` - All the business logic for running async tasks, shared between `runner` + `parser`
=> Split parser binary out from runner

cmd/server/BUILD.bazel, cmd/server/main.go, deps.bzl, go.mod, go.sum
This is a follow-up to making the credential service support site-granular (and email-granular) ACLs, enforcing it for PACTA.
=> Enforce the "sites" JWT claim for PACTA

WORKSPACE, async/async.go, cmd/runner/configs/local.conf, cmd/runner/main.go, cmd/server/main.go, db/sqldb/golden/human_readable_schema.sql, db/sqldb/golden/schema_dump.sql, db/sqldb/migrations/0014_add_more_report_file_types.down.sql, db/sqldb/migrations/0014_add_more_report_file_types.up.sql, db/sqldb/sqldb_test.go, dockertask/dockertask.go, pacta/pacta.go, reportsrv/reportsrv.go, reportsrv/reportsrv_test.go, scripts/run_server.sh
This PR updates the async task runner to support the new base image (which comes from [1]).
This includes things like:
- Uploading the new output directories (summaries + analysis)
- Fixing report paths so we can render the new reports
- Adding support for the new file types that show up in these new reports
- Supporting the new input formats (the benchmark + pacta-data dirs, input JSON, env vars, etc)
Importantly, this makes the new create-report image work **locally**, but doesn't do the Azure bits. That'll come in the next PR.
[1] https://github.com/rmi-pacta/workflow.pacta.webapp/pkgs/container/workflow.pacta.webapp
=> Integrate latest report generation Docker image into site

scripts/BUILD.bazel, scripts/jumphost.sh
This PR adds a simple `jumphost.sh` script that creates an Azure VM and then tunnels through it to allow local `psql` usage.
=> Add a jumphost VM creation script

.github/workflows/deploy.yml
This is a fix for #209
The gist is that we host the sample CSV, e.g. at https://pacta.dev.rmi.siliconally.dev/samples/sample-1.csv
Currently, on dev, that file contains:
```
version https://git-lfs.github.com/spec/v1
oid sha256:abdb709396bff1337709b6eb7bc26cde547615d88a619f5c9846fde1fb585335
size 131685
```
Which is just the LFS pointer to the actual file. This PR enables downloading LFS files when the GH Actions run checks out the repo
It also updates the version for other actions we use in the workflow
=> Pull LFS files in deploy workflow

.github/workflows/deploy.yml, cmd/server/configs/test.conf, frontend/envs/env.test, frontend/package.json, frontend/swa-cli.config.json
- Creates/updates relevant configs (mostly frontend)
- Moves our GH Actions deploy workflow to point at RMI's Azure
=> Last set of tweaks for RMI Azure deployment

.github/workflows/deploy.yml, WORKSPACE, async/async.go, azure/aztask/aztask.go, cmd/parser/configs/test.conf, cmd/parser/main.go, cmd/runner/configs/test.conf, db/sqldb/golden/human_readable_schema.sql, db/sqldb/golden/schema_dump.sql, db/sqldb/migrations/0015_add_more_report_file_types.down.sql, db/sqldb/migrations/0015_add_more_report_file_types.up.sql, db/sqldb/sqldb_test.go, pacta/pacta.go, taskrunner/taskrunner.go
This PR updates the runner base image to fix something I noticed in an Azure run that the RMI folk have since fixed.
There have been some small format tweaks in the mean time:
- More file types outputted by the report generation flow
- `Files` is now an array of strings
=> Update runner base image + tweaks to support it

WORKSPACE, async/async.go, cmd/runner/configs/dev.conf, cmd/runner/configs/local.conf, cmd/runner/configs/test.conf, cmd/runner/main.go, frontend/components/analysis/AccessButtons.vue, frontend/components/portfolio/ListView.vue, frontend/lang/en.json, taskrunner/taskrunner.go
This PR adds all the stuff needed for running audits:
- Updating the `runner_base` image to the newest version
- Interfacing with the `run_audit.sh` script
- Assorted UX tweaks
- Mostly because I don't think there's anything to 'View' like for Reports and Dashboards, so we just offer the download button
- Also hide the download button for not-completed runs
=> Add support for audits
